# Generated by Django 5.0.1 on 2024-08-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Flat', 'Flat'), ('Duplex', 'Duplex'), ('Bungalow', 'Bungalow'), ('Townhouse', 'Townhouse'), ('Rooftop', 'Rooftop'), ('Building', 'Building'), ('Commercial', 'Commercial'), ('Shop', 'Shop')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
